services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    image: pi-car
    platform: linux/arm64/v8
    build: .
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
